kind: pipeline
name: default

# Pipeline for putting cloudformation files into S3 for nested stacks
steps:
  - name: build
    image: eignhpants/docker-go-build
    commands:
      - ./build/build.sh
